Feature/i2c
whatis777/bno055 pull request #1
Opened 2021-01-06 15:24 UTC by whatis777

The following list contains the points that I implemented so far. 
The code will not yet work, as it is untested up to now regarding a real bno055 test.
This merge-request is about finding an architectural consens how the project could be structured in future

- package structure bno055/bnp055 is now as if generated by ROS2
- introduced classe-based / OOP architecture
- extended README.doc
- extracted UART functionality to UARTConnector; unspecific connection functionality is located in the parent class Connector. So it can be extended for I2C implementation
- extracted ROS node parameter handling into separate class
- extracted BNO-055 API into separate service class SensorService, so we have a separation in code between technical implementation and "business logic"

- fixed some ROS2 runtime issues in package.xml and setup.py
- fixed some TODOs (for instance extracting the register constants)
- fixed default values assignment to parameters if no parameter file is loaded
- eliminated dead / erroneous code (i.e. shutdown() or rospy.logerror(), ...)

- introduced I2C dummy

2021-01-06 16:18 UTC, flynneva commented on bno055/bno055.py
> +        if self.param.connection_type.value == UARTConnector.CONNECTIONTYPE_UART:
i really like this approach. great idea!

2021-01-06 16:33 UTC, flynneva requested changes
wow, overall amazing work!!!! this is a huge improvement to the code and a great place to build from.

let me know what you think of the idomatic comments/suggestions I made....feel free to ignore them as well - it is very minor and not a big deal, just it might save us some typing later on 😄

2021-01-06 16:33 UTC, flynneva commented on bno055/connectors/Connector.py
> +from bno055 import bno055_registers
since we are importing this from bno055, do we need to name the register file `bno055_registers`? might make more sense just to leave it as a plain `registers.py`

2021-01-06 16:33 UTC, flynneva commented on bno055/connectors/Connector.py
> +from bno055 import bno055_registers
```suggestion
from bno055 import registers
```

2021-01-06 16:33 UTC, flynneva commented on bno055/bno055_registers.py
> +
see below comments, but since this file is already in the `bno055` directory, can we just rename it to `registers.py`?

2021-01-06 16:33 UTC, flynneva commented on bno055/connectors/Connector.py
> +        Receives data packages from the sensor
i like these comments you added....will you want to add sphinx documentation to this repo eventually or something similar?

2021-01-06 16:33 UTC, flynneva commented on bno055/connectors/I2CConnector.py
> +from bno055.connectors.Connector import Connector
same as the register comment, but would it make more sense to rename this file just to `i2c.py` since it is already in the connector directory?

2021-01-06 16:33 UTC, flynneva commented on bno055/connectors/I2CConnector.py
> +class I2CConnector(Connector):
renaming to just `I2C` might make more sense, no?
```suggestion
class I2C(Connector):
```

2021-01-06 16:33 UTC, flynneva commented on bno055/connectors/UARTConnector.py
> +# Connector for UART integration of the BNO-055
same as before, might be more idomatic to be just `UART.py` since it is already in the `connectors` directory

2021-01-06 16:33 UTC, flynneva commented on package.xml
> +  <version>1.0.0</version>
since this is still in development, maybe lets only bump minor version numbers until we reach a "decent" freeze point to release a major 1.0.0 release.
```suggestion
  <version>0.1.0</version>
```

2021-01-06 16:33 UTC, flynneva commented on setup.py
> +    version='1.0.0',
same as above, minor version for now until we reach a more mature phase.

```suggestion
    version='0.1.0',
```

2021-01-06 16:36 UTC, flynneva commented
from the CI it looks like there are still 142 flake8 errors that we could fix with this big update as well. might be a good idea to knock those out as well to have a "clean" starting point for future work.

ill see what I can do for the flake8 errors

2021-01-06 17:17 UTC, whatis777 commented on bno055/connectors/Connector.py
> +from bno055 import bno055_registers
good pont

2021-01-06 17:22 UTC, whatis777 commented on bno055/connectors/Connector.py
> +        Receives data packages from the sensor
as I'm new to python, I didn't know this sphinx tool :-) but it sounds good. Even without it, IntelliJ is capable to resolve the API documentation when pressing Ctrl+q on a selected item.
Let's add this later, when there's more functionality added

2021-01-06 17:27 UTC, whatis777 commented on bno055/connectors/I2CConnector.py
> +from bno055.connectors.Connector import Connector
done

2021-01-06 17:27 UTC, whatis777 commented on bno055/connectors/I2CConnector.py
> +class I2CConnector(Connector):
done

2021-01-06 17:28 UTC, whatis777 commented on package.xml
> +  <version>1.0.0</version>
done

2021-01-06 17:28 UTC, whatis777 commented on setup.py
> +    version='1.0.0',
done

2021-01-06 17:41 UTC, flynneva commented
if you'd like to run the CI lint test locally you can run it from the command line with:
```
ament_flake8
```

from within your cloned bno055 directory. eventually we can add other ament tests like `ament_copyright` and `ament_pep257`

2021-01-06 18:09 UTC, whatis777 commented on bno055/bno055.py
> +        if self.param.connection_type.value == UARTConnector.CONNECTIONTYPE_UART:
thx :-)

2021-01-06 18:09 UTC, whatis777 commented on bno055/connectors/UARTConnector.py
> +# Connector for UART integration of the BNO-055
done

2021-01-14 23:23 UTC, flynneva approved these changes
LGTM

2021-01-15 13:22 UTC, merged